services:
  - type: worker
    name: giveaway-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scanner.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false 